# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
server:
  port: 28080

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
